name: academia_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  custom_rounded_rectangle_border: ^0.3.0

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  feather_icons: ^1.2.0
  logger: ^2.0.2+1

  flutter_modular: ^6.3.2
  dotted_border: any
  flutter_mobx: any
  mobx: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: any
  build_runner: any
  mobx_codegen: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true
  assets:
    - assets/
